---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shinyproxy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shinyproxy-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shinyproxy-rb
subjects:
- kind: ServiceAccount
  name: shinyproxy-sa
  namespace: shinyproxy
roleRef:
  kind: ClusterRole
  name: shinyproxy-role
  apiGroup: rbac.authorization.k8s.io